# Enables the "Sponsor" button on the repo.
github: [Verisonder]
# Add others once you set them up, e.g.:
# ko_fi: your_kofi_name
# buy_me_a_coffee: your_bmac_name
# custom: ["https://paypal.me/yourname"]
